const english = {
  easypezy: 'Easypezy',
  home: 'Home',
  notification: 'Notification',
  sale: 'Sale',
  rental: 'Rental',
  other: 'Other',
  saved: 'Saved',
  profile: 'Profile',
  login: 'Login',
  logout: 'Logout',
  signup: 'Signup',
  //post a place
  postNew: 'Add New',
  selectCatagory: 'select',
  forRental: 'For Rental',
  forSale: 'For Sale',
  forOther: 'Other Catagory',
  headingForItem: 'Item Heading',
  example: 'Eg:',
  houseForSale: 'House for Sale',
  roomForRent: 'Room for Rent',
  itemDescription: 'Item Description',
  itemDescriptionLong: 'Tell us whats great about your item',
};
const nepali = {
  easypezy: 'ईजीपीजी',
  home: 'पहिलो पाना',
  notification: 'सूचना',
  sale: 'बिक्री',
  rental: 'भाडा',
  other: 'अन्य',
  saved: 'भण्डारित',
  profile: 'प्रोफाइल',
  login: 'लगइन',
  logout: 'लगआउट',
  signup: 'खाता बनाउनुहोस्',
  //post a place
  postNew: 'नयाँ थप्नुहोस्',
  selectCatagory: 'क्याटागोरी चयन गर्नुहोस्',
  forRental: 'भाडाका लागि',
  forSale: 'बिक्रीका लागि',
  forOther: 'अन्य क्याटागोरी',
  headingForItem: 'तपाईंको वस्तुको लागि शीर्षक',
  example: 'उदाहरण',
  houseForSale: 'घर बिक्रीमा छ',
  roomForRent: 'भाडाको लागि कोठा',
  itemDescription: 'वस्तु विवरण',
  itemDescriptionLong: 'वर्णनमा तपाईंको वस्तुको बारेमा लेख्नुहोस्',
};

// ईजीपीजी;
