export const data = {
  createdAt: '2020-09-15T22:57:07.882Z',
  available: true,
  itemImgUrl: [
    'https://firebasestorage.googleapis.com/v0/b/easypezy-39664.appspot.com/o/items%2Fkf4jxb1i1600210348-other%2FScreenShot2020-09-15at3.51.25PM.png?alt=media',
    'https://firebasestorage.googleapis.com/v0/b/easypezy-39664.appspot.com/o/items%2Fkf4jxb1i1600210348-other%2FManakamana-Temple-in-Nepal-Hike-on-Treks.jpg?alt=media',
    'https://firebasestorage.googleapis.com/v0/b/easypezy-39664.appspot.com/o/items%2Fkf4jxb1i1600210348-other%2Fdaily-manakamana-tour37.jpg?alt=media',
  ],
  hasPrice: true,
  itemId: 'kf4jxb1i1600210348-other',
  saveByOtherCount: 0,
  userHandle: 'prakash123',
  contactNo: '+977 0808080878',
  likeCount: 1,
  selectApply: [
    'Cablecar Service',
    'another service',
    'Second service',
    'third service',
    'Second service',
    'third service',
  ],
  nearbyPlace: [
    'Manakamana Temple',
    'school places',
    'basundhara store',
    'new new newplaces',
  ],
  commentCount: 0,
  address: {
    district: 'Gorkha',
    address: 'Manakamana Temple',
    city: 'Manakamana',
  },
  type: 'place',
  negotiable: true,
  pointDescription: [
    'Best place to visit is one of the great places',
    'New places is something i want to know',
  ],
  priceRange: '1000',
  description:
    'The Manakamana Temple situated in the Gorkha district of Nepal is the sacred place of the Hindu Goddess Bhagwati, an incarnation of Parvati.',
  showNum: true,
  viewCount: 127,
  reportCount: 0,
  userImage:
    'https://firebasestorage.googleapis.com/v0/b/easypezy-39664.appspot.com/o/432460898702.JPG?alt=media&token=6c828e4e-32e1-49ee-b0bd-b42e5318aa87',
  catagory: 'other',
  userData: {
    fullName: 'Prakash Acharya',
    email: 'pracharya2601@gmail.com',
  },
  name: 'Manakamana Temple',
};
